# -*- coding: utf-8 -*-
"""meteo.ipynb

Automatically generated by Colaboratory and Gitbox.

Original file is located at
    https://colab.research.google.com/drive/1PcwNlAyZxnhssbuZBdHXc2_-zt_0kp12

# Meteorológiai jelentés

Emelt érettségi 2020. május
[Algoritmizálás, adatmodellezés](https://drive.google.com/file/d/1gx0MH4x3cEOi10eFUB-muRWxAK7LV3Mr/view?usp=sharing)

### 1. Olvassa be és tárolja el a tavirathu13.txt állomány adatait!
"""

#első feladat
URL=""
tavirathu13=open(URL+"tavirathu13.txt")
tavirat=[]
for sor in tavirathu13:
  tavirat.append(sor.strip().split(" ")) #szétbontjuk a sort
  tavirat[-1][3]=int(tavirat[-1][3])     #a hőmérsékletet egész számmá alakítjuk
tavirathu13.close()

"""### 2. Kérje be a felhasználótól egy város kódját! Adja meg, hogy az adott városból mikor érkezett az utolsó mérési adat! A kiírásban az időpontot óó:pp formátumban jelenítse meg!"""

#második feladat
print("2. feladat")
varos=input("Adja meg egy település kódját: ").upper()
for i in range(-1,-len(tavirat)-1,-1):  #a végéről visszafele keressük a várost
  if varos==tavirat[i][0]:
    print("Az utolsó adat a megadott településről {}:{}-kor érkezett.".format(tavirat[i][1][0:2],tavirat[i][1][2:4]))
    break                               #ha megtaláltuk, befejezzük a ciklust

"""### 3. Határozza meg, hogy a nap során mikor mérték a legalacsonyabb és a legmagasabb hőmérsékletet! Jelenítse meg a méréshez kapcsolódó település nevét, az időpontot és a hőmérsékletet! Amennyiben több legnagyobb vagy legkisebb érték van, akkor elég az egyiket kiírnia."""

#harmadik feladat
print("3. feladat")
minho=tavirat[0][3]
maxho=tavirat[0][3]
minindex=0
maxindex=0
for i in range(1,len(tavirat)):
  if minho>tavirat[i][3]:
    minho=tavirat[i][3]
    minindex=i
  if maxho<tavirat[i][3]:
    maxho=tavirat[i][3]
    maxindex=i
print("Legalacsonyabb hőmérséklet: {} {}:{} {} fok".format(tavirat[minindex][0],tavirat[minindex][1][0:2],tavirat[minindex][1][2:4],tavirat[minindex][3]))
print("Legmagasabb hőmérséklet   : {} {}:{} {} fok".format(tavirat[maxindex][0],tavirat[maxindex][1][0:2],tavirat[maxindex][1][2:4],tavirat[maxindex][3]))

"""### 4. Határozza meg, azokat a településeket és időpontokat, ahol és amikor a mérések idején szélcsend volt! (A szélcsendet a táviratban 00000 kóddal jelölik.) Ha nem volt ilyen, akkor a „Nem volt szélcsend a mérések idején.” szöveget írja ki! A kiírásnál a település kódját és az időpontot jelenítse meg."""

#negyedik feladat
print("4. feladat")
szelcsendvolt=False
for sor in tavirat:
  if sor[2]=="00000":
    szelcsendvolt=True
    print("{} {}:{}".format(sor[0],sor[1][0:2],sor[1][2:4]))
if not szelcsendvolt:
  print("Nem volt szélcsend a mérések idején.")

"""### 5. Határozza meg a települések napi középhőmérsékleti adatát és a hőmérséklet-ingadozását! A kiírásnál a település kódja szerepeljen a sor elején a minta szerint! A kiírásnál csak a megoldott feladatrészre vonatkozó szöveget és értékeket írja ki!
a.) A középhőmérséklet azon hőmérsékleti adatok átlaga, amikor a méréshez tartozó óra értéke 1., 7., 13., 19. Ha egy településen a felsorolt órák valamelyikén nem volt mérés, akkor a kiírásnál az „NA” szót jelenítse meg! Az adott órákhoz tartozó összes adat átlagaként határozza meg a középhőmérsékletet, azaz minden értéket azonos súllyal vegyen figyelembe! A középhőmérsékletet egészre kerekítve jelenítse meg!

b.) A hőmérséklet-ingadozás számításhoz az adott településen a napi legmagasabb és legalacsonyabb hőmérséklet különbségét kell kiszámítania! (Feltételezheti, hogy minden település esetén volt legalább két mérési adat.)
"""

#ötödik feladat
print("5. feladat")

#ez a függvény kivágja az óra értéket
def ora(oraperc):
  return(oraperc[0:2])

#ez a függvény egy listában levő számok átlagát számolja ki
def atlag(lista):
  return(sum(lista)/len(lista))

varosok=[]      #kigyűjtjük a város kódokat
for sor in tavirat:
  if sor[0] not in varosok:
    varosok.append(sor[0])

for varos in varosok:     #minden városra kigyűjtjük
  osszes_meres=[]         #az összes mérést
  meresek=[]              #a megadott órákban végzett mérést
  orak=[]                 #az 01, 07, 13, 19 időpontokat
  for sor in tavirat:
    if varos==sor[0]:
      osszes_meres.append(sor[3])
      if ora(sor[1])=="01" or ora(sor[1])=="07" or ora(sor[1])=="13" or ora(sor[1])=="19":
        meresek.append(sor[3])
        if ora(sor[1]) not in orak:
          orak.append(ora(sor[1]))
  if len(orak)==4:
    print("{} középhőmérséklet: {:.0f} fok, ".format(varos,atlag(meresek)),end="")
  else:
    print("{} NA,                       ".format(varos),end="")
  print("Hőmérséklet-ingadozás: {}".format(max(osszes_meres)-min(osszes_meres)))

"""### 6. Hozzon létre településenként egy szöveges állományt, amely első sorában a település kódját tartalmazza! A további sorokban a mérési időpontok és a hozzá tartozó szélerősségek jelenjenek meg! A szélerősséget a minta szerint a számértéknek megfelelő számú kettőskereszttel (#) adja meg! A fájlban az időpontokat és a szélerősséget megjelenítő kettőskereszteket szóközzel válassza el egymástól! A fájl neve X.txt legyen, ahol az X helyére a település kódja kerüljön!"""

#hatodik feladat
print("6. feladat")

def szelero(adat):   #egy szélerősség adatból visszad egy kettőskeresztekből álló szöveget
  erosseg=""
  for e in range(0,int(adat[3:])):
    erosseg+="#"
  return(erosseg)

for varos in varosok:
  varos_file=URL+varos+".txt"
  kiiras=open(varos_file,mode="w")
  kiiras.write(varos+"\n")
  for sor in tavirat:
    if varos==sor[0]:
      kiiras.write("{}:{} {}\n".format(sor[1][0:2],sor[1][2:4],szelero(sor[2])))
  kiiras.close()
